{
 "title": "Job view",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "JID", "query": "${VAR_JID}" },
   { "name": "Name", "query": "${VAR_NAME}" },
   { "name": "traceID", "query": "${VAR_TRACEID}" }
  ]
 },
 "panels": [
  {
   "title": "SORTED JOB STATES",
   "type": "pgillich-tree-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    id,\n    CASE WHEN (result IS true AND changes IS false) THEN 'unchanged'\n    WHEN (result IS false) THEN 'failed'\n    WHEN (result IS true AND changes IS true) THEN 'changed'\n    END status,\n    state,\n    jsonb_pretty(return::jsonb) AS return\nFROM states\nWHERE jid='$JID';\n"
    }
   ]
  },
  {
   "title": "JOB DURATION TIME ",
   "type": "timeseries",
   "description": "Display the duration of all job runs with the same name to understand the job duration over time",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "salt_duration{job_name=\"$Name\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "TRACE VIEW",
   "type": "traces",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "query": "$traceID", "search": "jid=$JID" }
   ]
  },
  {
   "title": "JOB CACHE DATA",
   "type": "gapit-htmlgraphics-panel",
   "description": "Display a complete JSON message returned by the corresponding Salt job. You can expand or collapse JSON sections.",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT jsonb_pretty(full_ret::jsonb) AS full_ret\nFROM salt_returns\nWHERE jid = '$JID'"
    }
   ]
  }
 ]
}