{
 "title": "Salt / Jobs Overview",
 "tags": [
  "salt",
  "salt-observ-lib"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RECENT JOB RUNS",
   "type": "table",
   "description": "Display the recent job runs, with the most recent at the top. Click on the link in the job_name column to see the job details.\n\nFor more information on this panel, please visit https://grafana.com/docs/grafana/latest/visualizations/table/",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"salt_events\"} | json"
    }
   ]
  },
  {
   "title": "JOB STATS",
   "type": "piechart",
   "description": "The job stats panel visualizes the percentage of successful vs failed job runs, plus the total number of runs. This visualization is based on the chosen time range.\n\nFor more information on this panel, please visit https://grafana.com/docs/grafana/latest/visualizations/gauge-panel/",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"salt_events\"} | json | success = `false` [$__range]))",
     "legendFormat": "Number of job success equal false",
     "resolution": 1
    },
    {
     "expr": "sum(count_over_time({job=\"salt_events\"} [$__range]))",
     "legendFormat": "Total job"
    },
    {
     "expr": "sum(count_over_time({job=\"salt_events\"} | json | success = `true` [$__range]))",
     "legendFormat": "true"
    }
   ]
  },
  {
   "title": "JOB SUCCESS",
   "type": "timeseries",
   "description": "Visualize the number of successful and failed job runs within each 5 minute interval.\nThe x-axis represents the time period, and the y-axis is the number of jobs. Hover your mouse over any of the bars to see the jobs count.\n\nFor more information on this panel, please visit https://grafana.com/docs/grafana/latest/visualizations/time-series/",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"salt_events\"} | json | success = `false` [$__interval]))",
     "legendFormat": "false"
    },
    {
     "expr": "sum(count_over_time({job=\"salt_events\"} | json | success = `true` [$__interval]))",
     "legendFormat": "true"
    }
   ]
  },
  {
   "title": "JOB DURATION DISTRIBUTION OVER TIME",
   "type": "heatmap",
   "description": "Visualize the job duration distribution over time.\nThe x-axis represents the time range, and the y-axis is the sum of the job durations. This visualization is based on the chosen interval.\n\nFor more information on this panel, please visit https://grafana.com/docs/grafana/latest/visualizations/heatmap/",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(sum_over_time(salt_job_duration_seconds{job_name=~\".+\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}