#!/usr/bin/env python3
"""Generate docs/libs.md from the observ-lib index: each lib's dashboard title,
signal/query count, and panel count, grouped to mirror the alloy module tree."""
import json
import os

import _jsonnet

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "libs.md")

GROUPS = {
    "Runtimes": ["runtimes.golang", "runtimes.jvm", "runtimes.python", "runtimes.dotnet", "runtimes.nodejs"],
    "System": ["system.linux", "system.docker", "system.windows"],
    "Kubernetes": ["kubernetes.pod", "kubernetes.cadvisor"],
    "Databases": [
        "databases.sql.postgres", "databases.sql.mysql",
        "databases.kv.redis", "databases.kv.memcached", "databases.kv.etcd",
    ],
    "Monitoring": [
        "monitoring.prometheus", "monitoring.mimir", "monitoring.loki",
        "monitoring.tempo", "monitoring.pyroscope",
    ],
    "Collector": ["collector.alloy"],
    "Cross-cutting": ["alerts", "logs"],
}


def info(path):
    snip = (
        f"local o=(import 'g.libsonnet').libs.{path}.new({{}});"
        "{ title: o.config.dashboardTitle,"
        "  signals: (if std.objectHas(o,'signals') then std.length(std.objectFields(o.signals))"
        "            else if std.objectHas(o,'queries') then std.length(std.objectFields(o.queries)) else 0),"
        "  panels: std.length(std.objectFields(o.grafana.dashboard.toResource().spec.elements)) }"
    )
    return json.loads(_jsonnet.evaluate_snippet("t", snip, jpathdir=[ROOT]))


def main():
    lines = [
        "# observ-libs",
        "",
        "_Generated by `scripts/gen-libs-docs.py` — do not edit by hand._",
        "",
        "Each observ-lib (`libs/<name>-observ-lib`) is `new(config) -> { signals,",
        "grafana:{dashboard,...}, asMonitoringMixin() }`, built on **common-lib** and",
        "the v2 builder. Reach them at `g.libs.<group>.<name>`.",
        "",
    ]
    for group, paths in GROUPS.items():
        lines += [f"## {group}", "", "| `g.libs.…` | Dashboard | Signals | Panels |", "|---|---|---|---|"]
        for p in paths:
            try:
                d = info(p)
                lines.append(f"| `{p}` | {d['title']} | {d['signals']} | {d['panels']} |")
            except Exception as exc:  # noqa: BLE001
                lines.append(f"| `{p}` | _(error: {str(exc).splitlines()[0]})_ | | |")
        lines.append("")

    lines += [
        "## common-lib",
        "",
        "The shared base every observ-lib builds on (`g.common.*`):",
        "",
        "- **`signal`** — the **signal engine** rendered through our v2 viz: `init` / `addSignal` (gauge/counter/histogram/info/raw/log/stub) + the lean `signal.new()` facade; `as*` panels & targets + variable generation (`getVariables*`, `queriesSelector*`, multi/single instance).",
        "- **`panels`** — 56 base panel presets across 8 categories (see [Chart types](panels.md)).",
        "- **`annotations`** — annotation primitives (base + critical/warning/info/fatal/reboot/serviceFailed), built from a signal target.",
        "- **`tokens`** — colour + timeSeries styling tokens; **`utils`** — label→selector/legend/URL helpers + `chainLabels`.",
        "- **`signals`**, **`rows`**, **`library`** — common signal presets + element groups.",
        "- **`alert`**, **`logs`**, **`deploy`** — reusable alert-rule / log-panel / deploy-annotation primitives.",
        "- **`pack`** — the observ-lib build contract.",
        "",
    ]
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    total = sum(len(v) for v in GROUPS.values())
    print(f"wrote {OUT}: {total} observ-libs")


if __name__ == "__main__":
    main()
