#!/usr/bin/env python3
"""Generate docs/panels.md from the chart-type definitions: the common-lib base
panel presets (with their viz type + unit) and the reference variation boards."""
import json
import os

import _jsonnet

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "panels.md")
CATEGORIES = ["generic", "cpu", "memory", "disk", "network", "system", "requests", "hardware"]
TD = "[g.query.base('grafana-testdata-datasource',{scenarioId:'random_walk'})+g.query.withDatasource('testdata')]"


def ev(s):
    return json.loads(_jsonnet.evaluate_snippet("t", s, jpathdir=[ROOT]))


def preset_info(cat, name):
    snip = (
        f"local g=import 'g.libsonnet'; local t={TD};"
        f"local p=g.common.panels.{cat}.{name}('Demo', t); p.spec.vizConfig"
    )
    try:
        vc = ev(snip)
        return vc["group"], vc["spec"]["fieldConfig"]["defaults"].get("unit") or "—"
    except Exception:  # noqa: BLE001
        return "?", "—"


def main():
    lines = [
        "# Chart types & variations",
        "",
        "_Generated by `scripts/gen-panel-docs.py` — do not edit by hand._",
        "",
        "Two layers of chart definitions:",
        "",
        "- **Base presets** (`libs/common-lib/panels/`) — pre-styled panels per category,",
        "  `g.common.panels.<category>.<preset>(title, targets, description)`.",
        "- **Variation boards** (`reference/panels/`) — a tabbed board per Grafana panel",
        "  type showing its options (rendered in the Panel Reference folder).",
        "",
        "## Base presets",
        "",
    ]
    for cat in CATEGORIES:
        names = ev(f"std.objectFields((import 'g.libsonnet').common.panels.{cat})")
        lines += [f"### {cat}", "", "| Preset | Viz | Unit |", "|--------|-----|------|"]
        for name in names:
            kind, unit = preset_info(cat, name)
            lines.append(f"| `{name}` | {kind} | {unit} |")
        lines.append("")

    lines += ["## Variation boards", "",
              "Each Grafana panel type has a tabbed reference board: an **Overview** tab",
              "(description + Grafana docs link) then one tab per option variation.", ""]
    boards = ev("import 'reference/render.jsonnet'")
    panels = {k: v for k, v in boards.items() if k.startswith("panel-")}
    lines += ["| Panel type | Variation tabs |", "|------------|----------------|"]
    for name in sorted(panels):
        b = panels[name]
        title = b["spec"]["title"].replace("Panel / ", "")
        lay = b["spec"]["layout"]
        tabs = [t["spec"]["title"] for t in lay["spec"]["tabs"]][1:] if lay["kind"] == "TabsLayout" else []
        lines.append(f"| {title} | {', '.join(tabs) if tabs else '—'} |")
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    total = sum(len(ev(f"std.objectFields((import 'g.libsonnet').common.panels.{c})")) for c in CATEGORIES)
    print(f"wrote {OUT}: {total} presets, {len(panels)} variation boards")


if __name__ == "__main__":
    main()
