#!/usr/bin/env python3
"""Render scenarios/catalog.jsonnet and write a multi-document Backstage catalog
YAML (Domain + Systems + Components) to backstage/observ-viz-catalog.yaml.

Usage:  python3 scripts/gen-catalog.py
"""
import json
import os

import _jsonnet
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "backstage", "observ-viz-catalog.yaml")


def main():
    entities = json.loads(
        _jsonnet.evaluate_file(os.path.join(ROOT, "scenarios", "catalog.jsonnet"), jpathdir=[ROOT])
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("# Generated by scripts/gen-catalog.py — do not edit by hand.\n")
        yaml.safe_dump_all(entities, fh, sort_keys=False, default_flow_style=False)
    kinds = {}
    for e in entities:
        kinds[e["kind"]] = kinds.get(e["kind"], 0) + 1
    print(f"wrote {OUT}: {len(entities)} entities {kinds}")


if __name__ == "__main__":
    main()
